const { app, BrowserWindow, Tray, Menu, nativeImage, dialog, shell, ipcMain } = require('electron');
const { spawn } = require('child_process');
const path = require('path');
const fs = require('fs');
const log = require('electron-log');
const { autoUpdater } = require('electron-updater');

// ─── Configuration ──────────────────────────────────────────────────────────────

const APP_NAME = 'PureTec POS';
const PHP_PORT = 8000;
const isDev = process.argv.includes('--dev') || !app.isPackaged;

// Paths
const appDataDir = path.join(app.getPath('userData'));
const dbDir = path.join(appDataDir, 'database');
const dbPath = path.join(dbDir, 'database.sqlite');
const logsDir = path.join(appDataDir, 'logs');
const storageDir = path.join(appDataDir, 'storage');

// Resource paths (different in dev vs production)
const resourcesPath = isDev
  ? path.join(__dirname, '..')
  : path.join(process.resourcesPath, 'laravel');

// Resolve PHP path
let phpPath;
if (isDev) {
  // Use bundled PHP if available in electron/php/php.exe, otherwise fall back to system 'php'
  const localPhp = path.join(__dirname, 'php', 'php.exe');
  if (fs.existsSync(localPhp)) {
    phpPath = localPhp;
  } else {
    phpPath = 'php';
  }
} else {
  phpPath = path.join(process.resourcesPath, 'php', 'php.exe');
}

// ─── Logger Setup ───────────────────────────────────────────────────────────────

log.transports.file.resolvePathFn = () => path.join(logsDir, 'puretec-pos.log');
log.transports.file.maxSize = 5 * 1024 * 1024; // 5MB
log.info('App starting...');
log.info(`App Data Dir: ${appDataDir}`);
log.info(`Dev Mode: ${isDev}`);
log.info(`Resources Path: ${resourcesPath}`);

// ─── State ──────────────────────────────────────────────────────────────────────

let mainWindow = null;
let splashWindow = null;
let phpProcess = null;
let tray = null;
let isQuitting = false;

// ─── Ensure Directories ─────────────────────────────────────────────────────────

function ensureDirectories() {
  const dirs = [
    dbDir,
    logsDir,
    storageDir,
    path.join(storageDir, 'app', 'public'),
    path.join(storageDir, 'framework', 'cache'),
    path.join(storageDir, 'framework', 'cache', 'data'),
    path.join(storageDir, 'framework', 'sessions'),
    path.join(storageDir, 'framework', 'views'),
    path.join(storageDir, 'logs'),
  ];

  dirs.forEach(dir => {
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
      log.info(`Created directory: ${dir}`);
    }
  });
}

// Helper to get environment variables for PHP/Laravel processes
function getLaravelEnv() {
  return {
    ...process.env,
    APP_URL: `http://127.0.0.1:${PHP_PORT}`,
    DB_CONNECTION: 'sqlite',
    DB_DATABASE: dbPath,
    ELECTRON_STORAGE_PATH: storageDir,
    APP_SERVICES_CACHE: path.join(storageDir, 'framework', 'cache', 'services.php'),
    APP_PACKAGES_CACHE: path.join(storageDir, 'framework', 'cache', 'packages.php'),
    APP_CONFIG_CACHE: path.join(storageDir, 'framework', 'cache', 'config.php'),
    APP_ROUTES_CACHE: path.join(storageDir, 'framework', 'cache', 'routes-v7.php'),
    APP_EVENTS_CACHE: path.join(storageDir, 'framework', 'cache', 'events.php'),
  };
}

// ─── Environment File ───────────────────────────────────────────────────────────

function setupEnvironment() {
  // In dev mode, create a separate .env.electron.local override file
  // In production, modify the bundled .env
  const envPath = isDev
    ? path.join(resourcesPath, '.env.electron.local')
    : path.join(resourcesPath, '.env');

  // Update database path dynamically
  const dbPathNormalized = dbPath.replace(/\\/g, '/');
  const storagePathNormalized = storageDir.replace(/\\/g, '/');

  const servicesCachePathNormalized = path.join(storageDir, 'framework', 'cache', 'services.php').replace(/\\/g, '/');
  const packagesCachePathNormalized = path.join(storageDir, 'framework', 'cache', 'packages.php').replace(/\\/g, '/');
  const configCachePathNormalized = path.join(storageDir, 'framework', 'cache', 'config.php').replace(/\\/g, '/');
  const routesCachePathNormalized = path.join(storageDir, 'framework', 'cache', 'routes-v7.php').replace(/\\/g, '/');
  const eventsCachePathNormalized = path.join(storageDir, 'framework', 'cache', 'events.php').replace(/\\/g, '/');

  if (isDev) {
    // In dev mode, just create an override file (Laravel loads .env by default,
    // but we pass env vars directly to PHP process anyway)
    const overrideContent = `# Auto-generated by Electron - DO NOT EDIT
APP_URL=http://127.0.0.1:${PHP_PORT}
DB_CONNECTION=sqlite
DB_DATABASE="${dbPathNormalized}"
ELECTRON_STORAGE_PATH="${storagePathNormalized}"
APP_SERVICES_CACHE="${servicesCachePathNormalized}"
APP_PACKAGES_CACHE="${packagesCachePathNormalized}"
APP_CONFIG_CACHE="${configCachePathNormalized}"
APP_ROUTES_CACHE="${routesCachePathNormalized}"
APP_EVENTS_CACHE="${eventsCachePathNormalized}"
`;
    fs.writeFileSync(envPath, overrideContent);
    log.info(`Electron env override written to: ${envPath}`);
  } else {
    // In production, modify the bundled .env
    let envContent = '';
    if (fs.existsSync(envPath)) {
      envContent = fs.readFileSync(envPath, 'utf-8');
    }

    // Helper to replace or append
    const setEnvVar = (key, value) => {
      const regex = new RegExp(`^${key}=.*`, 'm');
      if (envContent.match(regex)) {
        envContent = envContent.replace(regex, `${key}="${value}"`);
      } else {
        envContent += `\n${key}="${value}"`;
      }
    };

    setEnvVar('DB_DATABASE', dbPathNormalized);
    setEnvVar('ELECTRON_STORAGE_PATH', storagePathNormalized);
    setEnvVar('APP_SERVICES_CACHE', servicesCachePathNormalized);
    setEnvVar('APP_PACKAGES_CACHE', packagesCachePathNormalized);
    setEnvVar('APP_CONFIG_CACHE', configCachePathNormalized);
    setEnvVar('APP_ROUTES_CACHE', routesCachePathNormalized);
    setEnvVar('APP_EVENTS_CACHE', eventsCachePathNormalized);

    // Set APP_URL
    envContent = envContent.replace(
      /APP_URL=.*/,
      `APP_URL=http://127.0.0.1:${PHP_PORT}`
    );

    fs.writeFileSync(envPath, envContent);
  }

  log.info(`Database path: ${dbPathNormalized}`);
}

// ─── Database Setup ─────────────────────────────────────────────────────────────

function setupDatabase() {
  return new Promise((resolve, reject) => {
    let isBrandNewDb = false;
    // Create empty SQLite database if it doesn't exist
    if (!fs.existsSync(dbPath)) {
      fs.writeFileSync(dbPath, '');
      log.info(`Created empty SQLite database: ${dbPath}`);
      isBrandNewDb = true;
    }

    // Run migrations
    const artisanPath = path.join(resourcesPath, 'artisan');
    const migrateProcess = spawn(phpPath, [artisanPath, 'migrate', '--force'], {
      cwd: resourcesPath,
      env: getLaravelEnv(),
    });

    let output = '';
    migrateProcess.stdout.on('data', (data) => {
      output += data.toString();
      log.info(`Migration: ${data.toString().trim()}`);
    });

    migrateProcess.stderr.on('data', (data) => {
      log.warn(`Migration stderr: ${data.toString().trim()}`);
    });

    migrateProcess.on('close', (code) => {
      if (code === 0) {
        log.info('Migrations completed successfully');
        
        if (isBrandNewDb) {
          log.info('Fresh database detected. Running seeders...');
          const seedProcess = spawn(phpPath, [artisanPath, 'db:seed', '--force'], {
            cwd: resourcesPath,
            env: getLaravelEnv(),
          });

          seedProcess.stdout.on('data', (data) => {
            log.info(`Seeding: ${data.toString().trim()}`);
          });

          seedProcess.on('close', (seedCode) => {
            if (seedCode === 0) {
              log.info('Database seeded successfully');
              resolve();
            } else {
              log.error(`Seeding failed with code ${seedCode}`);
              resolve();
            }
          });
        } else {
          resolve();
        }
      } else {
        log.error(`Migration failed with code ${code}: ${output}`);
        resolve();
      }
    });

    migrateProcess.on('error', (err) => {
      log.error(`Migration process error: ${err.message}`);
      resolve();
    });
  });
}

// ─── PHP Server ─────────────────────────────────────────────────────────────────

function startPhpServer() {
  return new Promise((resolve, reject) => {
    const publicPath = path.join(resourcesPath, 'public');

    log.info(`Starting PHP server: ${phpPath}`);
    log.info(`Public path: ${publicPath}`);
    log.info(`Port: ${PHP_PORT}`);

    phpProcess = spawn(phpPath, [
      '-S', `127.0.0.1:${PHP_PORT}`,
      '-t', publicPath,
      path.join(resourcesPath, 'server.php'),
    ], {
      cwd: resourcesPath,
      env: getLaravelEnv(),
      stdio: ['pipe', 'pipe', 'pipe'],
    });

    phpProcess.stdout.on('data', (data) => {
      log.info(`PHP: ${data.toString().trim()}`);
    });

    phpProcess.stderr.on('data', (data) => {
      const msg = data.toString().trim();
      // PHP built-in server logs requests to stderr
      if (msg && !msg.includes('Accepted') && !msg.includes('Closing')) {
        log.info(`PHP: ${msg}`);
      }
    });

    phpProcess.on('error', (err) => {
      log.error(`PHP process error: ${err.message}`);
      reject(err);
    });

    phpProcess.on('close', (code) => {
      log.info(`PHP server exited with code ${code}`);
      if (!isQuitting) {
        // Restart PHP server if it crashes
        log.warn('PHP server crashed, restarting in 2 seconds...');
        setTimeout(() => {
          startPhpServer().catch(err => log.error('Failed to restart PHP:', err));
        }, 2000);
      }
    });

    // Wait for server to be ready
    const checkServer = (attempts = 0) => {
      if (attempts > 60) {
        reject(new Error('PHP server did not start within 30 seconds'));
        return;
      }

      const http = require('http');
      const req = http.get(`http://127.0.0.1:${PHP_PORT}/login`, (res) => {
        // Accept any response (200, 302, etc.) as server being ready
        log.info(`PHP server ready (status: ${res.statusCode})`);
        res.resume(); // Consume response to free up memory
        resolve();
      });

      req.on('error', () => {
        setTimeout(() => checkServer(attempts + 1), 500);
      });

      req.setTimeout(2000, () => {
        req.destroy();
        setTimeout(() => checkServer(attempts + 1), 500);
      });
    };

    // Give PHP a moment to start before checking
    setTimeout(() => checkServer(), 1500);
  });
}

function stopPhpServer() {
  if (phpProcess) {
    log.info('Stopping PHP server...');
    phpProcess.kill('SIGTERM');

    // Force kill after 3 seconds if still running
    setTimeout(() => {
      if (phpProcess && !phpProcess.killed) {
        phpProcess.kill('SIGKILL');
      }
    }, 3000);

    phpProcess = null;
  }
}

// ─── Splash Screen ──────────────────────────────────────────────────────────────

function createSplashWindow() {
  splashWindow = new BrowserWindow({
    width: 480,
    height: 360,
    frame: false,
    transparent: true,
    resizable: false,
    center: true,
    alwaysOnTop: true,
    skipTaskbar: true,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  const splashPath = isDev
    ? path.join(__dirname, 'splash.html')
    : path.join(__dirname, 'splash.html');

  splashWindow.loadFile(splashPath);
  splashWindow.on('closed', () => { splashWindow = null; });
}

// ─── Main Window ────────────────────────────────────────────────────────────────

function createMainWindow() {
  mainWindow = new BrowserWindow({
    width: 1400,
    height: 900,
    minWidth: 1024,
    minHeight: 680,
    title: APP_NAME,
    show: false,
    icon: getIconPath(),
    autoHideMenuBar: true,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      nodeIntegration: false,
      contextIsolation: true,
      spellcheck: false,
    },
  });

  // Remove default menu
  mainWindow.setMenu(null);

  // Load the Laravel app
  mainWindow.loadURL(`http://127.0.0.1:${PHP_PORT}`);

  // Show when ready
  mainWindow.once('ready-to-show', () => {
    if (splashWindow) {
      splashWindow.close();
    }
    mainWindow.show();
    mainWindow.focus();
  });

  // Handle external links - open in default browser
  mainWindow.webContents.setWindowOpenHandler(({ url }) => {
    if (url.startsWith('http') && !url.includes('127.0.0.1')) {
      shell.openExternal(url);
      return { action: 'deny' };
    }
    return { action: 'allow' };
  });

  // Handle window close
  mainWindow.on('close', (event) => {
    if (!isQuitting) {
      event.preventDefault();
      mainWindow.hide();
    }
  });

  mainWindow.on('closed', () => {
    mainWindow = null;
  });

  // Open DevTools in dev mode
  if (isDev) {
    mainWindow.webContents.openDevTools();
  }
}

// ─── System Tray ────────────────────────────────────────────────────────────────

function createTray() {
  const iconPath = getIconPath();
  let trayIcon;

  try {
    trayIcon = nativeImage.createFromPath(iconPath);
    trayIcon = trayIcon.resize({ width: 16, height: 16 });
  } catch (e) {
    log.warn('Could not load tray icon, using default');
    trayIcon = nativeImage.createEmpty();
  }

  tray = new Tray(trayIcon);
  tray.setToolTip(APP_NAME);

  const contextMenu = Menu.buildFromTemplate([
    {
      label: 'Open PureTec POS',
      click: () => {
        if (mainWindow) {
          mainWindow.show();
          mainWindow.focus();
        }
      },
    },
    { type: 'separator' },
    {
      label: 'Open POS Terminal',
      click: () => {
        if (mainWindow) {
          mainWindow.loadURL(`http://127.0.0.1:${PHP_PORT}/pos`);
          mainWindow.show();
          mainWindow.focus();
        }
      },
    },
    {
      label: 'Open Dashboard',
      click: () => {
        if (mainWindow) {
          mainWindow.loadURL(`http://127.0.0.1:${PHP_PORT}/dashboard`);
          mainWindow.show();
          mainWindow.focus();
        }
      },
    },
    { type: 'separator' },
    {
      label: 'Open Data Folder',
      click: () => {
        shell.openPath(appDataDir);
      },
    },
    {
      label: 'View Logs',
      click: () => {
        shell.openPath(path.join(logsDir, 'puretec-pos.log'));
      },
    },
    { type: 'separator' },
    {
      label: 'Check for Updates',
      click: () => {
        autoUpdater.checkForUpdatesAndNotify();
      },
    },
    { type: 'separator' },
    {
      label: 'Quit PureTec POS',
      click: () => {
        isQuitting = true;
        app.quit();
      },
    },
  ]);

  tray.setContextMenu(contextMenu);

  tray.on('double-click', () => {
    if (mainWindow) {
      mainWindow.show();
      mainWindow.focus();
    }
  });
}

// ─── Auto Updater ───────────────────────────────────────────────────────────────

function setupAutoUpdater() {
  autoUpdater.logger = log;
  autoUpdater.autoDownload = false;

  autoUpdater.on('update-available', (info) => {
    dialog.showMessageBox(mainWindow, {
      type: 'info',
      title: 'Update Available',
      message: `A new version (${info.version}) of PureTec POS is available.`,
      detail: 'Would you like to download and install it now?',
      buttons: ['Download', 'Later'],
      defaultId: 0,
    }).then((result) => {
      if (result.response === 0) {
        autoUpdater.downloadUpdate();
      }
    });
  });

  autoUpdater.on('update-downloaded', () => {
    dialog.showMessageBox(mainWindow, {
      type: 'info',
      title: 'Update Ready',
      message: 'Update has been downloaded. The application will restart to apply the update.',
      buttons: ['Restart Now', 'Later'],
      defaultId: 0,
    }).then((result) => {
      if (result.response === 0) {
        isQuitting = true;
        autoUpdater.quitAndInstall();
      }
    });
  });

  autoUpdater.on('error', (err) => {
    log.error('AutoUpdater error:', err);
  });

  // Check for updates after launch (with delay)
  setTimeout(() => {
    autoUpdater.checkForUpdatesAndNotify().catch(err => {
      log.info('Update check skipped:', err.message);
    });
  }, 10000);
}

// ─── Helper ─────────────────────────────────────────────────────────────────────

function getIconPath() {
  if (isDev) {
    return path.join(__dirname, '..', 'public', 'icons', 'icon-192.svg');
  }
  // In production, try multiple icon locations
  const iconPaths = [
    path.join(__dirname, 'build', 'icon.ico'),
    path.join(process.resourcesPath, 'laravel', 'public', 'icons', 'icon-192.svg'),
  ];
  for (const p of iconPaths) {
    if (fs.existsSync(p)) return p;
  }
  return iconPaths[0];
}

// ─── IPC Handlers ───────────────────────────────────────────────────────────────

function setupIpcHandlers() {
  // App version
  ipcMain.handle('get-version', () => {
    return app.getVersion();
  });

  // Window Controls
  ipcMain.on('window-minimize', () => {
    if (mainWindow) mainWindow.minimize();
  });

  ipcMain.on('window-maximize', () => {
    if (mainWindow) {
      if (mainWindow.isMaximized()) {
        mainWindow.unmaximize();
      } else {
        mainWindow.maximize();
      }
    }
  });

  ipcMain.on('window-close', () => {
    if (mainWindow) mainWindow.close();
  });

  // Notifications
  ipcMain.on('show-notification', (event, { title, body }) => {
    const { Notification } = require('electron');
    if (Notification.isSupported()) {
      new Notification({ title, body }).show();
    }
  });

  // Standard Print
  ipcMain.on('print', (event) => {
    const webContents = event.sender;
    webContents.print({ silent: false });
  });

  // Silent Print
  ipcMain.handle('print-silent', async (event, options) => {
    const { url, silent = true, deviceName = '', ...printOptions } = options || {};
    if (!url) {
      throw new Error('URL is required for silent printing');
    }

    return new Promise((resolve, reject) => {
      const printWindow = new BrowserWindow({
        show: false,
        webPreferences: {
          nodeIntegration: false,
          contextIsolation: true,
        }
      });

      printWindow.loadURL(url);

      printWindow.webContents.once('did-finish-load', () => {
        const opt = {
          silent: silent,
          deviceName: deviceName,
          printBackground: true,
          ...printOptions
        };

        printWindow.webContents.print(opt, (success, errorType) => {
          printWindow.destroy();
          if (success) {
            resolve({ success: true });
          } else {
            reject(new Error(`Print failed: ${errorType}`));
          }
        });
      });

      printWindow.webContents.once('did-fail-load', (e, errorCode, errorDescription) => {
        printWindow.destroy();
        reject(new Error(`Failed to load URL: ${errorDescription}`));
      });
    });
  });

  // File Dialogs
  ipcMain.handle('open-file-dialog', async (event, options) => {
    return await dialog.showOpenDialog(mainWindow, options);
  });

  ipcMain.handle('save-file-dialog', async (event, options) => {
    return await dialog.showSaveDialog(mainWindow, options);
  });

  // App Lifecycle
  ipcMain.on('restart-app', () => {
    app.relaunch();
    app.exit(0);
  });

  ipcMain.on('check-updates', () => {
    autoUpdater.checkForUpdatesAndNotify();
  });
}

// ─── App Lifecycle ──────────────────────────────────────────────────────────────

// Prevent multiple instances
const gotTheLock = app.requestSingleInstanceLock();

if (!gotTheLock) {
  app.quit();
} else {
  app.on('second-instance', () => {
    if (mainWindow) {
      if (mainWindow.isMinimized()) mainWindow.restore();
      mainWindow.show();
      mainWindow.focus();
    }
  });

  app.whenReady().then(async () => {
    log.info('Electron app ready');
    setupIpcHandlers();

    try {
      // 1. Show splash screen
      createSplashWindow();

      // 2. Ensure directories exist
      ensureDirectories();

      // 3. Setup environment
      setupEnvironment();

      // 4. Setup database (run migrations)
      await setupDatabase();

      // 5. Start PHP server
      await startPhpServer();

      // 6. Create main window
      createMainWindow();

      // 7. Create system tray
      createTray();

      // 8. Setup auto-updater
      setupAutoUpdater();

      log.info('App fully initialized');
    } catch (error) {
      log.error('Failed to start application:', error);

      if (splashWindow) splashWindow.close();

      dialog.showErrorBox(
        'PureTec POS - Startup Error',
        `Failed to start the application:\n\n${error.message}\n\nPlease check the log file at:\n${path.join(logsDir, 'puretec-pos.log')}`
      );

      app.quit();
    }
  });

  app.on('before-quit', () => {
    isQuitting = true;
    stopPhpServer();
  });

  app.on('window-all-closed', () => {
    // Don't quit when all windows closed (stays in tray)
  });

  app.on('activate', () => {
    if (mainWindow === null) {
      createMainWindow();
    } else {
      mainWindow.show();
    }
  });
}
